matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.4

dist: trusty
sudo: true
language:
  - cpp
compiler:
  - clang

before_install:
  - eval "${MATRIX_EVAL}"
  - git submodule update --init --recursive;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y;
      sudo apt-get update -qq;
      sudo apt-get install -qq cmake build-essential;
      sudo pip install -v cmake==3.12.*;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew upgrade cmake;
    fi

script:
  - export PATH=/usr/local/bin:$PATH
  - (cd xpdf/; git am ../xpdf-patches/*.patch)
  - gcc -v && g++ -v && cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Release ./;
  - make;

notifications:
  email: true
