name: CI

on:
  push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq cmake build-essential clang

      - name: Set up dependencies for macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew upgrade cmake

      - name: Display versions
        run: |
          gcc -v
          g++ -v
          cmake --version

      - name: set env variables
        if: runner.os == 'macOS'
        run: |
          echo "C_INCLUDE_PATH=/usr/local/include" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/usr/local/include" >> $GITHUB_ENV
      - name: Build
        run: |
          cmake ./
          make
