name: Memory analyzer (Valgrind)
on: [push]

jobs:
    build:
      strategy:
        matrix:
          os: [ ubuntu-22.04 ]

        fail-fast: false

      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: Set up dependencies for Linux
          run: |
            sudo apt-get update -qq
            sudo apt-get install -qq cmake build-essential clang icu-devtools


        - name: Build on Linux
          run: |
            cmake ./
            make

        - name: Valgrind Checker
          uses: Ximaz/valgrind-action@1.2.1
          with:
            binary_path: '.'